version: "3.9"
services:
  app:
    build: .
    container_name: mz-cms-api
    ports:
      - 8010:8000
    #restart: always
    volumes:
      - ${PWD}:/app
    networks:
      - db

networks:
  db:
    external: true
    name: de-containers_default